### PR TITLE
frens gentx.json

### PR DESCRIPTION
**Pull request by marcmacmac**

### CODE REVIEW

**Comment by marcmacmac** [comment]
hey @anilCSE,

tests didn't go through. Do you have any idea why? gentx.json looks valid to me. Is the test flaky and we rerun it or should we resubmit?

Cheers

**Comment by anilCSE** [comment]
Did you use the same account that was submitted in the validator form? Looks like this is an issue with the account  which is not part of the genesis accounts

**Comment by marcmacmac** [comment]
hey @anilCSE, thanks for getting on this so fast. indeed, i just double checked and we used a different account, which we don't want to use for it.
any chance to change it without making too much trouble?

**Comment by anilCSE** [comment]
> hey @anilCSE, thanks for getting on this so fast. indeed, i just double checked and we used a different account, which we don't want to use for it. any chance to change it without making too much trouble?

I see. I believe we can update your validator account this time. Can you dm your old account address on discord so we don't messup updating the genesis. You can keep this gentx as-is. I will update the genesis and retry this.

**Comment by marcmacmac** [comment]
i wrote you in discrod Marc#7309

**Pull request merged**
